development:
  adapter: mysql2
  encoding: utf8
  database: my_dev
  pool: 5
  username: root
  password: mysql
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: book_test
  pool: 5
  username: root
  password: mysql
  socket: /var/run/mysqld/mysqld.sock
